"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InvoicePaidEmail = void 0;
var jsx_runtime_1 = require("react/jsx-runtime");
var components_1 = require("@react-email/components");
var logo_1 = require("../components/logo");
var theme_1 = require("../components/theme");
var InvoicePaidEmail = function (_a) {
    var _b = _a.customerName, customerName = _b === void 0 ? "Customer" : _b, _c = _a.teamName, teamName = _c === void 0 ? "BaseOne" : _c, _d = _a.invoiceNumber, invoiceNumber = _d === void 0 ? "INV-0001" : _d, _e = _a.amount, amount = _e === void 0 ? "1,000.00" : _e, _f = _a.currency, currency = _f === void 0 ? "USD" : _f, _g = _a.paymentDate, paymentDate = _g === void 0 ? "2024-01-30" : _g, _h = _a.paymentMethod, paymentMethod = _h === void 0 ? "Bank Transfer" : _h, _j = _a.link, link = _j === void 0 ? "https://app.baseone.local/i/1234567890" : _j, logoUrl = _a.logoUrl, companyName = _a.companyName;
    var text = "Payment Received: Invoice ".concat(invoiceNumber, " - Thank you!");
    var themeClasses = (0, theme_1.getEmailThemeClasses)();
    var lightStyles = (0, theme_1.getEmailInlineStyles)("light");
    return ((0, jsx_runtime_1.jsx)(theme_1.EmailThemeProvider, { preview: (0, jsx_runtime_1.jsx)(components_1.Preview, { children: text }), children: (0, jsx_runtime_1.jsx)(components_1.Body, { className: "my-auto mx-auto font-sans ".concat(themeClasses.body), style: lightStyles.body, children: (0, jsx_runtime_1.jsxs)(components_1.Container, { className: "my-[40px] mx-auto p-[20px] max-w-[600px] ".concat(themeClasses.container), style: {
                    borderStyle: "solid",
                    borderWidth: 1,
                    borderRadius: 8,
                    borderColor: lightStyles.container.borderColor,
                }, children: [(0, jsx_runtime_1.jsx)(logo_1.Logo, { logoUrl: logoUrl, companyName: companyName || teamName }), (0, jsx_runtime_1.jsxs)(components_1.Heading, { className: "text-[21px] font-normal text-center p-0 my-[30px] mx-0 ".concat(themeClasses.heading), style: { color: "#059669" }, children: ["Payment Received! ", (0, jsx_runtime_1.jsx)("br", {}), "Invoice ", invoiceNumber] }), (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsxs)("span", { className: "font-medium ".concat(themeClasses.text), style: { color: lightStyles.text.color }, children: ["Hi ", customerName, ","] }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: themeClasses.text, style: { color: lightStyles.text.color }, children: ["Great news! We have successfully received your payment for invoice ", invoiceNumber, ". Thank you for your prompt payment."] }), (0, jsx_runtime_1.jsxs)(components_1.Section, { className: "my-[20px] p-[16px] bg-green-50 border border-green-200 rounded-lg", children: [(0, jsx_runtime_1.jsx)(components_1.Text, { className: "m-0 font-medium text-green-800", children: "Payment Details:" }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: "mt-[8px] mb-0 text-green-700", children: ["\u2022 Invoice Number: ", invoiceNumber, (0, jsx_runtime_1.jsx)("br", {}), "\u2022 Amount Paid: ", currency, " ", amount, (0, jsx_runtime_1.jsx)("br", {}), "\u2022 Payment Date: ", paymentDate, (0, jsx_runtime_1.jsx)("br", {}), paymentMethod && "\u2022 Payment Method: ".concat(paymentMethod)] })] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: themeClasses.text, style: { color: lightStyles.text.color }, children: "Your account has been updated and this invoice is now marked as paid. You can view the updated invoice and download a receipt using the button below." }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: themeClasses.text, style: { color: lightStyles.text.color }, children: "We appreciate your business and look forward to continuing to work with you." }), (0, jsx_runtime_1.jsx)(components_1.Section, { className: "text-center mt-[50px] mb-[50px]", children: (0, jsx_runtime_1.jsx)(theme_1.Button, { href: link, children: "View Receipt" }) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: "text-[12px] ".concat(themeClasses.mutedText), style: { color: lightStyles.mutedText.color }, children: ["This is a confirmation email from ", teamName, ". Please keep this email for your records."] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-[12px] ".concat(themeClasses.mutedText), style: { color: lightStyles.mutedText.color }, children: "If you have any questions about this payment or need assistance, please don't hesitate to contact our support team." }), (0, jsx_runtime_1.jsx)("br", {})] }) }) }));
};
exports.InvoicePaidEmail = InvoicePaidEmail;
exports.default = exports.InvoicePaidEmail;
